In [14]:
import numpy as np

def arr(A,B):
    if len(A)>len(B):
        f=A
        a=B
        pass
    else:
        f=B
        a=A
    modf = 0
    insr = 0
    delt = 0
    f = " "+f
    a = " "+a
    arr = [[0]*(len(a))]*(len(f))
    arr = np.array(arr)
    Divide = (len(a)-1)
    for i in  range(1,len(f)):
        arr[i][0] = i
        for j in range(1,len(a)):
            arr[0][j] = j
            #같으면 대각선위의 값 가져옴
            if f[i] ==a[j]:
                arr[i][j]=arr[i-1][j-1]
            #다르면 왼쪽, 왼 대각위, 위 중 최소값 +1
            else:
                arr[i][j]= 1+ (min(arr[i-1][j],arr[i][j-1],arr[i-1][j-1]))                
    return arr[len(f)-1][len(a)-1], arr

f = "대한 민국"
s = ["한국", "코리아", "대한민국", "고려","대한이 만세 민국이"]
i=0
while i<len(s):
    
    최소비용,chart = arr(f,s[i])
    print(f,"v.s",s[i])
    print(chart)
    print("최소비용 : ",최소비용)
    print()
    i+=1
        

대한 민국 v.s 한국
[[0 1 2]
 [1 1 2]
 [2 1 2]
 [3 2 2]
 [4 3 3]
 [5 4 3]]
최소비용 :  3

대한 민국 v.s 코리아
[[0 1 2 3]
 [1 1 2 3]
 [2 2 2 3]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
최소비용 :  5

대한 민국 v.s 대한민국
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 0 1 2]
 [3 2 1 1 2]
 [4 3 2 1 2]
 [5 4 3 2 1]]
최소비용 :  1

대한 민국 v.s 고려
[[0 1 2]
 [1 1 2]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
최소비용 :  5

대한 민국 v.s 대한이 만세 민국이
[[ 0  1  2  3  4  5]
 [ 1  0  1  2  3  4]
 [ 2  1  0  1  2  3]
 [ 3  2  1  1  2  3]
 [ 4  3  2  1  2  3]
 [ 5  4  3  2  2  3]
 [ 6  5  4  3  3  3]
 [ 7  6  5  4  4  4]
 [ 8  7  6  5  4  5]
 [ 9  8  7  6  5  4]
 [10  9  8  7  6  5]]
최소비용 :  5



In [9]:
import numpy as np

def arr(A,B):
    if len(A)>len(B):
        f=A
        a=B
        pass
    else:
        f=B
        a=A
    modf = 0
    insr = 0
    delt = 0
    f = " "+f
    a = " "+a
    arr = [[0]*(len(a))]*(len(f))
    arr = np.array(arr)
    Divide = (len(a)-1)
    for i in  range(1,len(f)):
        arr[i][0] = i
        for j in range(1,len(a)):
            arr[0][j] = j
            #같으면 대각선위의 값 가져옴
            if f[i] ==a[j]:
                arr[i][j]=arr[i-1][j-1]
            #다르면 왼쪽, 왼 대각위, 위 중 최소값 +1
            else:
                arr[i][j]= 1+ (min(arr[i-1][j],arr[i][j-1],arr[i-1][j-1]))
    print(arr)
                
   
    return arr[len(f)-1][len(a)-1], modf//Divide, insr//Divide, delt//Divide, arr

f = "가나다라"
s = "가마바라"
i=0
while i<len(s):
    
    최소비용,변경,삽입,삭제,chart = arr(f,s)
    print(f,"v.s",s)
    print(chart)
    print("최소비용 : ",최소비용,"변경: ",변경,"삽입",삽입,"삭제",삭제)
    print()
    i+=1
        

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
가나다라 v.s 가마바라
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
최소비용 :  2 변경:  0 삽입 0 삭제 0

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
가나다라 v.s 가마바라
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
최소비용 :  2 변경:  0 삽입 0 삭제 0

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
가나다라 v.s 가마바라
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
최소비용 :  2 변경:  0 삽입 0 삭제 0

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
가나다라 v.s 가마바라
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 2 3]
 [3 2 2 2 3]
 [4 3 3 3 2]]
최소비용 :  2 변경:  0 삽입 0 삭제 0

