In [159]:
import numpy as np

def arr(A,B):
    if len(A)>len(B):
        f=A
        a=B
        pass
    else:
        f=B
        a=A
    modf = 0
    insr = 0
    delt = 0
    f = " "+f
    a = " "+a
    arr = [[0]*(len(a))]*(len(f))
    arr = np.array(arr)
    Divide = (len(a)-1)
    for i in  range(1,len(f)):
        arr[i][0] = i
        for j in range(1,len(a)):
            arr[0][j] = j
            if i > Divide: #비교경우
                #삽입할 경우 그러나, 삽입할 위치보다 전에 빈공  
                if f[i]:
                    arr[i][j] = arr[i][j-1]+1
                    insr +=1
                    print("insr",insr)
                    print("f[i] and a[j]==\" \"",f[i],a[j])
                    print(arr)
                elif f[i] != " " and a[j] != " " and f[i]!=a[j]:
                    arr[i][j] = arr[i][j-1]+1
                    insr +=1
                    print("insr",insr)
                    print("f[i] and a[j]==\" \"",f[i],a[j])
                    print(arr)
            elif i ==len(a): #같은 인덱스
                if f[i] != " " and a[j] != " " and f[i] == a[j]:
                    arr[i][j] = arr[i-1][j-1]
                    print("f[i] == a[j]",f[i],a[j])
                    print(arr)

                elif f[i] != " " and a[j] != " " and f[i]!=a[j] :
                    arr[i][j] = arr[i-1][j-1]+1
                    modf +=1
                    print("modf",modf)
                    print("f[i] != a[j]",f[i],a[j],i,len(a))
                    print(arr)

                #삽입할 경우 그러나, 삽입할 위치보다 전에 빈공  
                elif f[i] and a[j]==" ":
                    arr[i][j] = arr[i][j-1]+1
                    insr +=1
                    print("insr",insr)
                    print("f[i] and a[j]==\" \"",f[i],a[j])
                    print(arr)

                elif f[i]==" " and a[j]:
                    arr[i][j] = arr[i-1][j]+1
                    delt +=1
                    print("delt",delt)
                    print("f[i]==\" \" and a[j]",f[i],a[j])
                    print(arr)
                    arr[i][j] = arr[i][j-1]
                
                
            elif i < len(a):
                
                if f[i] != " " and a[j] != " " and f[i] == a[j]:
                    arr[i][j] = arr[i-1][j-1]
                    print("f[i] == a[j]",f[i],a[j])
                    print(arr)

                elif f[i] != " " and a[j] != " " and f[i]!=a[j] :
                    arr[i][j] = arr[i-1][j-1]+1
                    modf +=1
                    print("modf",modf)
                    print("f[i] != a[j]",f[i],a[j],i,len(a))
                    print(arr)

                #삽입할 경우 그러나, 삽입할 위치보다 전에 빈공  
                elif f[i] and a[j]==" ":
                    arr[i][j] = arr[i][j-1]+1
                    insr +=1
                    print("insr",insr)
                    print("f[i] and a[j]==\" \"",f[i],a[j])
                    print(arr)

                elif f[i]==" " and a[j]:
                    arr[i][j] = arr[i-1][j]+1
                    delt +=1
                    print("delt",delt)
                    print("f[i]==\" \" and a[j]",f[i],a[j])
                    print(arr)
                    arr[i][j] = arr[i][j-1]
                
    
    print(delt, Divide)
    return arr[len(f)-1][len(a)-1], modf//Divide, insr//Divide, delt//Divide, arr

#f = "대한 민국"
#s = ["한국", "코리아", "대한민국", "고려","대한이 만세 민국이"]#
#s = ["코리아"]
f = "RELEVANT"
s = "ELEPHANT"
i=0
while i<len(s):
    
    최소비용,변경,삽입,삭제,chart = arr(f,s)
    print(f,"v.s",s)
    print(chart)
    print("최소비용 : ",최소비용,"변경: ",변경,"삽입",삽입,"삭제",삭제)
    print()
    i+=1
        
    
    


modf 1
f[i] != a[j] E R 1 9
[[0 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
f[i] == a[j] E E
[[0 1 2 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 2
f[i] != a[j] E L 1 9
[[0 1 2 3 0 0 0 0 0]
 [1 1 1 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
f[i] == a[j] E E
[[0 1 2 3 4 0 0 0 0]
 [1 1 1 3 3 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 3
f[i] != a[j] E V 1 9
[[0 1 2 3 4 5 0 0 0]
 [1 1 1 3 3 5 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0

modf 41
f[i] != a[j] A N 6 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 8]
 [3 3 2 3 1 5 5 7 8]
 [4 4 4 3 4 2 6 6 8]
 [5 5 5 5 4 5 3 7 7]
 [6 6 6 6 6 5 5 4 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 42
f[i] != a[j] A T 6 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 8]
 [3 3 2 3 1 5 5 7 8]
 [4 4 4 3 4 2 6 6 8]
 [5 5 5 5 4 5 3 7 7]
 [6 6 6 6 6 5 5 4 8]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 43
f[i] != a[j] N R 7 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 8]
 [3 3 2 3 1 5 5 7 8]
 [4 4 4 3 4 2 6 6 8]
 [5 5 5 5 4 5 3 7 7]
 [6 6 6 6 6 5 5 4 8]
 [7 7 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 44
f[i] != a[j] N E 7 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 8]
 [3 3 2 3 1 5 5 7 8]
 [4 4 4 3 4 2 6 6 8]
 [5 5 5 5 4 5 3 7 7]
 [6 6 6 6 6 5 5 4 8]
 [7 7 7 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 45
f[i] != a[j] N L 7 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 8]
 [3 3 2 3 1 5 5 7 8]
 [4 4 4 3 4

 [0 0 0 0 0 0 0 0 0]]
modf 9
f[i] != a[j] L E 2 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 10
f[i] != a[j] L V 2 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 11
f[i] != a[j] L A 2 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 12
f[i] != a[j] L N 2 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
modf 13
f[i] != a[j] L T 2 9
[[0 1 2 3 4 5 6 7 8]
 [1 1 1 3 3 5 6 7 8]
 [2 2 2 1 4 4 6 7 8]
 [0 0 0 0 0

In [15]:
arr = [range(len(a)+1)]*(len(f)+1)
arr = np.array(arr)

In [115]:
s = ["한국", "코리아", "대한 민국", "고려"]
s[2]

'대한 민국'

In [117]:
s[2][2] == " "

True